server:
  port: 8081
logging:
  level:
    com.onfishs.yshyauth: debug
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  type:
    aliases:
      package: com.onfishs.yshycore.auth.entity
spring:
  application:
    name: yshy-auth
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yshy_auth?serverTimezone=UTC&default-character-set=utf8
    username: root
    password: root
eureka:
  instance:
    hostname: yshy-auth
    instance-id: yshy-auth
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
  client:
    service-url:
      defaultZone: http://admin:enjoy@localhost:7001/eureka
info:
  app.name: yshy-auth
  company.name: yshy
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$

